# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main

pool:
  name: AgentLab4  # Your self-hosted agent name

variables:
  solutionPath: 'MvcMovie/MvcMovie.sln'  # Solution path relative to the repository root

steps:
  # Clone from GitHub
  - checkout: self  # Ensures latest code is pulled from the GitHub repo

  # Install .NET 8.0 SDK
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: '8.x'  # Change this to '8.x' for .NET 8.0 SDK
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Restore, Build, and Test
  - script: |
      dotnet restore "$(Build.SourcesDirectory)/$(solutionPath)"
      dotnet build "$(Build.SourcesDirectory)/$(solutionPath)" --configuration Release
      dotnet test "$(Build.SourcesDirectory)/$(solutionPath)"
    displayName: 'Restore, Build, and Test'

  # Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'






