# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main

pool:
  name: AgentLab4  # Your self-hosted agent name

variables:
  solutionPath: '$(Build.SourcesDirectory)/MvcMovie/MvcMovie/MvcMovie.sln'  # Full path to the solution file

steps:
  # Clone from GitHub
  - checkout: self  # Ensures latest code is pulled from the GitHub repo

  # Install .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: '7.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Restore, Build, and Test
  - script: |
      dotnet restore "$(solutionPath)"
      dotnet build "$(solutionPath)" --configuration Release
      dotnet test "$(solutionPath)"
    displayName: 'Restore, Build, and Test'

  # Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'




